apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app-pv
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-app-pv
  template:
    metadata:
      labels:
        app: react-app-pv
    spec:
      containers:
        - name: react-app-container
          image: parilvadher/react-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-pv-service
spec:
  type: ClusterIP
  selector:
    app: react-app-pv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
